Refactor: Remove bold Simplified log file handling

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -21,22 +21,17 @@ fi
 
 target_ip="$1:"
 domain_to_check=$2
-BOLD=$(tput bold)
-NORM=$(tput sgr0)
+log_file="$HOME/.logs/a-record-migration-$(date '+%Y-%m-%d-%H-%M-%S')-${domain_to_check}.log"
 
 # interval to check in minutes
 interval=5
 
-log_file=~/.logs/a-record-migration-$(date '+%Y-%m-%d-%H-%M-%S')-${domain_to_check}.log
+# Create the log file if it doesn't exist
+touch "$log_file" || { echo "Failed to create log file: $log_file"; exit 1; }
 
-exec 3>&1 1>>${log_file} 2>&1    # see https://stackoverflow.com/a/18462920/1870339
+echo "Checking for migration of ${domain_to_check} to ${target_ip} at ${interval}-minute intervals."
 
-check="Checking for migration of ${BOLD}${domain_to_check}${NORM} to ${BOLD}${target_ip}${NORM}"
-
-echo "${check} at ${interval}-minute intervals." 1>&3
-echo "${check}" 1>&2
-
-echo "==> Migration check started on $(date)" | tee /dev/fd/3
+echo "==> Migration check started on $(date)" | tee "$log_file"
 
 while true
 do
@@ -44,7 +39,7 @@ do
 
   if [ "$ip" = "${target_ip}" ]
   then
-    echo "==> Migration complete on $(date)\n--+--" | tee /dev/fd/3
+    echo "==> Migration complete on $(date)\n--+--" | tee -a "$log_file"
     exit 0
   else
     echo "==> Still pointing to ${BOLD}${ip}${NORM} @ $(date)" 1>&3
